### ISSUE TITLE
Parse from a HTML string instead of reader

### ISSUE THREAD

**Issue by TigerHix** [stefanhaustein/HtmlView2#1]
I'm wondering is this possible? I have tried

`processor.parse(BufferedReader(ByteArrayInputStream("abc".toByteArray(Charset.defaultCharset())).reader(Charset.defaultCharset())), htmlView) // Also tried using UTF-8`

but it throws a runtime exception:

`E/AndroidRuntime(24645): Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT abc@1:4 in java.io.BufferedReader@2573efd)`

Thanks in advance. This is an awesome library!

**Comment by stefanhaustein** [comment]
Should work if you add some more markup, e.g.
"<html><body>abc</body></html>"

Tiger Tang notifications@github.com schrieb am Di., 2. Aug. 2016, 19:42:

**Comment by TigerHix** [comment]
Thanks! The exception is now gone. However it seems like some character styles are not rendered correctly on my Android 6.0.1...? (e.g. **bold** and _italics_)

![screenshot_20160803-021226](https://cloud.githubusercontent.com/assets/3406505/17339722/cabe9224-591f-11e6-87a9-365f25620903.png)

**Comment by stefanhaustein** [comment]
As it seems to work at top level (bold titles), I guess for some style flags need to go into the typeFace case below: https://github.com/stefanhaustein/HtmlView2/blob/master/htmlview2/src/main/java/org/kobjects/htmlview2/SpanCollection.java#L63

Will adjust this later today.

**Comment by stefanhaustein** [comment]
Was actually a mixup of element.style and element.computedStyle, see https://github.com/stefanhaustein/HtmlView2/commit/31e60ab10d3ffe223d85797c674d54439683f0df

Fixed at head.

**Comment by TigerHix** [comment]
Thank you! Now it works like a charm. Is there a way to use custom fonts?

**Comment by stefanhaustein** [comment]
You'd probably need to extend https://github.com/stefanhaustein/HtmlView2/blob/master/htmlview2/src/main/java/org/kobjects/htmlview2/CssConversion.java for custom fonts.

**Comment by stefanhaustein** [comment]
Clean solution would probably be to add "registerFont(name, typeface)" to the HtmlView class
