### ISSUE TITLE
change nested tag color

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#10]
in this html:

```
<p style="color:green">
    salam
    <span style="color:red !important">
        simple text
    </span>
</p>
```

close and open parent tags don't resolve my problem any time because it can't be extends some propertise such as color,font face or other things from parent. 
for example:
```
<p style="color:green">
    salam
    </p>
        <span>
            simple text
        </span>
    <p>
</p>
```

how can i change nested tag as : `span`

**Comment by stefanhaustein** [comment]
Thanks for the test case! I can reproduce the problem (everything is green), but don't have a fix yet.

**Comment by pishguy** [comment]
It cauae of resolve many problems of android programers.thanks

**Comment by stefanhaustein** [comment]
Should be fixed at head: 
![issue10](https://cloud.githubusercontent.com/assets/4282319/25277733/35839160-26a0-11e7-82c6-9e19ed9e5df3.png)

**Comment by pishguy** [comment]
@stefanhaustein oh man! thank you very much

**Comment by stefanhaustein** [comment]
p.s. you may need to remove "!important", I don't think it's valid syntax at this position....

**Comment by pishguy** [comment]
@stefanhaustein yes its not valid syntax.I removed it
