### ISSUE TITLE
set html to textview

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#11]
how can i set parsed html to TextView instead of add view?

**Comment by stefanhaustein** [comment]
That's not possible, as the HTML may get parsed to multiple views.

Did you consider the built-in HTML capabilities of TextView? They might be sufficient for simple HTML, see http://stackoverflow.com/questions/2116162/how-to-display-html-in-textview

**Comment by pishguy** [comment]
yes sir, i tested that. unfortunately built-in html parser its not work
with your library and i like to use your library instead of that,

**Comment by pishguy** [comment]
@stefanhaustein oh i have a question. after add htmlview to other view, that can be selectable by user? for example select some character,word after parse to save or set that to other style as he want?

**Comment by stefanhaustein** [comment]
It's possible but you'll need your own method to do so.
Should look roughly like this:

    void makeSelectable(ViewGroup viewGroup) {
        for (int i = 0; i < viewGroup.getChildCount(); i++) {
           View child = viewGroup.getChildAt(i);
           if (child instanceof ViewGroup) {
             makeSelectable((ViewGroup) child);
           } else if (child instanceof TextView) {
             ((TextView) child).setTextIsSelectable(true);
           }
        }
      }

**Comment by pishguy** [comment]
its work fine, Thank you very much
