### ISSUE TITLE
using justify for text aligment

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#13]
this library can be support `text-align:justify;`? we have 2 direction LTR and RTL, RTL is for such as arabic language or china

**Comment by stefanhaustein** [comment]
Unfortunately, the Android TextView that's used internally does not support justified text. 
http://stackoverflow.com/questions/1292575/android-textview-justify-text

One option might be using this library based on TextView internally -- but it seems to have several open issues:
https://github.com/ufo22940268/android-justifiedtextview

**Comment by pishguy** [comment]
@stefanhaustein yes, thats right. you have right, the Android `TextView` that's used internally does not support justified text

**Comment by stefanhaustein** [comment]
One of the comments says it will be available in Android O. I hope it will get ported back to the support library then....
