### ISSUE TITLE
change background color inside <span>

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#14]
when i trying to use `background-color:#eee;` for `<span>` such as :
```
<span>
    It's to
    <span style="color:#00ff00;background-color:#eee;">do do do do</span> so
</span>
```

`background-color:#eee;` dont apply for this part of text, that work only on `<p>` tag, for example this html work fine 

```
<span>
    It's to
    <p style="color:#00ff00;background-color:#eee;">do do do do</p> so
</span>
```

**Comment by stefanhaustein** [comment]
Thanks for the report, should be fixed at head now with commit 067ff68
