### ISSUE TITLE
Access directly to web

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#16]
can i access directly to link on web? for example `http://mysite.com/help.html` to show and parse that without attaching to application or using `HttpConnection`

**Comment by stefanhaustein** [comment]
Without changes, links should open a regular browser (using an intent internally). If you want to load content in HtmlView, you'll need a HttpConnection, but it should be straightforward -- similar to the demo. See issue #17 for how to intercept clicks on links.
