### ISSUE TITLE
make a clickable text

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#17]
this code is simple way to make clickable part of string:

```
SpannableString ss = new SpannableString("Android is a Software stack");
ClickableSpan clickableSpan = new ClickableSpan() {
    @Override
    public void onClick(View textView) {
        startActivity(new Intent(MyActivity.this, NextActivity.class));
    }
    @Override
    public void updateDrawState(TextPaint ds) {
            super.updateDrawState(ds);
            ds.setUnderlineText(false);
        }
};
ss.setSpan(clickableSpan, 22, 27, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);

TextView textView = (TextView) findViewById(R.id.hello);
textView.setText(ss);
textView.setMovementMethod(LinkMovementMethod.getInstance());
textView.setHighlightColor(Color.TRANSPARENT);
```

now how can i implementing this feature for this library?

**Comment by stefanhaustein** [comment]
Subclass HtmlView and implement openLink: 
https://github.com/stefanhaustein/HtmlView2/blob/55a4056e00945867eb0f1f84228f80101c83ff32/htmlview2/src/main/java/org/kobjects/htmlview2/HtmlView.java#L211

**Comment by pishguy** [comment]
@stefanhaustein yes thats right. but i want to make custom clickable part of text with `ClickableSpan` not link into textview

**Comment by stefanhaustein** [comment]
That's tricky. What prevents you from using "regular" links?

**Comment by pishguy** [comment]
@stefanhaustein when we have regular link we can use that to open that with browser, but we can make simple clickable for part of text to show `Toast`, opening activity or get event to click on that, or for example we have book reader application, after make clickable for custom text or words, we have more ability to manage user to use book content such as make note,make clickable to show related posts or show toast

**Comment by stefanhaustein** [comment]
I think you can do this with links: Implement HtmlView.openLink in a subclass and examine the clicked element to decide whether to open the linked page or do something different. You could use special URLs to decide what to do, or set additional attributes on the element to trigger different actions...

**Comment by pishguy** [comment]
@stefanhaustein very well, could you tell me how can i do that?

**Comment by stefanhaustein** [comment]
Something like this:

    public void openLink(Element element, URI uri) {
        if (uri.getScheme().equals("toast")) {
           // add code to display toast based on the url / element here
        } else {
           super.openLink(element, uri);
        }
     }

Then use links like <a href="toast:ref"> to display toasts etc?

**Comment by pishguy** [comment]
@stefanhaustein i'm not sure this is my answer, you suppose i have this string:

`You’re receiving notifications because you authored the thread.`

and i want to clickable part of text such as : `the thread`

how can i use `ClickableSpan` to make that as clickable to show `Toast` or other event? or set tag for that to know which created part of text as links clicked by user, for example:

making clickable string such `notifications` and `authored the thread` in this string:
`You’re receiving notifications because you authored the thread.`

```
SpannableString ss = new SpannableString("You’re receiving notifications because you authored the thread.");
//notifications
ClickableSpan clickableSpan = new ClickableSpan() {
    @Override
    public void onClick(View textView) {
        Toast clicked on `notifications`
    }
    @Override
    public void updateDrawState(TextPaint ds) {
            super.updateDrawState(ds);
            ds.setUnderlineText(false);
        }
};
ss.setSpan(clickableSpan, 7, 17, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);

//authored the thread.
ClickableSpan clickableSpan = new ClickableSpan() {
    @Override
    public void onClick(View textView) {
        Toast clicked on `authored the thread`
    }
    @Override
    public void updateDrawState(TextPaint ds) {
            super.updateDrawState(ds);
            ds.setUnderlineText(false);
        }
};
ss.setSpan(clickableSpan, 29,50, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
```

**Comment by stefanhaustein** [comment]
Should work like this:

Markup:
    
    You’re receiving notifications because you authored
    <a href="toast:" label="The toast text">the thread</a>.

HtmlView subclass code:

    public void openLink(Element element, URI uri) {
      if (uri.getScheme().equals("toast")) {
         // If this is a special "toast" link, show the text in the label attribute as a toast
         Toast.makeText(context, element.getAttribute("label"), Toast.LENGHT_SHORT).show();
      } else {
         // Otherwise, just open the link
         super.openLink(element, uri);
      }
     }

**Comment by pishguy** [comment]
@stefanhaustein your mean is modify this method on your library?

```
  public void openLink(Element element, URI uri) {
    Intent intent = new Intent(Intent.ACTION_VIEW);
    intent.setData(Uri.parse(uri.toString()));
    getContext().startActivity(intent);
  }
```

**Comment by stefanhaustein** [comment]
You don't need to modify the library, you can use a subclass...

    class MyHtmlView extends HtmlView {
      @Override 
      public void openLink(Element element, URI uri) { 
          ...

**Comment by pishguy** [comment]
​ok, please let me to test that

**Comment by stefanhaustein** [comment]
Please reopen if you run into issues.

**Comment by pishguy** [comment]
@stefanhaustein could you help me how can i use customize link on this code:

i create simple project to know how can i use for example `toast:` instead of `htt://`

for below code i get this error: 

`java.lang.IllegalArgumentException: Expected scheme-specific part at index 6: toast:`

i use latest version as `v2.0.2`

my implemented code:
```
public class MainActivity extends AppCompatActivity {

    HtmlProcessor htmlProcessor = new HtmlProcessor();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            Reader reader = new StringReader("<a href=\"toast:\" label=\"The toast text\">the thread</a>");

            myClass htmlView = new myClass(this);
            htmlProcessor.parse(reader, htmlView);

            ScrollView scrollView = new ScrollView(this);
            scrollView.addView(htmlView);
            setContentView(scrollView);

        } catch (Exception e) {
            e.printStackTrace();
            Log.e("HtmlView ", e.getMessage());
            throw new RuntimeException(e);
        }
    }

    public class myClass extends HtmlView {

        public myClass(Context context) {
            super(context);
        }

        @Override
        public void openLink(Element element, URI uri) {
            if (uri.getScheme().equals("toast")) {
                // If this is a special "toast" link, show the text in the label attribute as a toast
                Toast.makeText(MainActivity.this, element.getAttribute("label"), Toast.LENGTH_LONG).show();
            } else {
                // Otherwise, just open the link
                super.openLink(element, uri);
            }
        }
    }
}
```

**Comment by FriedrichFroebel** [comment]
I cannot see any usage scenario which could require this as a toast is just shown for 3500 milliseconds when using `Toast.LENGTH_LONG`.

**Comment by pishguy** [comment]
@FriedrichFroebel problem is not `Toast` sir, even i can't show log in `LogCat`, i get error for toast on custom link not show `Toast` after click on that


`Process: ir.pishguy.htmlparser, PID: 15344  java.lang.IllegalArgumentException: Expected scheme-specific part at index 6: toast: at java.net.URI.create(URI.java:854) at java.net.URI.resolve(URI.java:1038) at org.kobjects.htmlview2.HtmlView.createUri(HtmlView.java:77)`

**Comment by stefanhaustein** [comment]
Looks like you need to add something behind the colon to make the "toast:" link a valid url.... Can you try "toast:toast"?

**Comment by pishguy** [comment]
@stefanhaustein yes, that work fine, thanks

**Comment by pishguy** [comment]
@stefanhaustein this feature dont work when textview is selectable
