### ISSUE TITLE
show image from real path

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#19]
You suppose i have some image into SDcard and i would like to show them on html, in sample of library image is into assets, but maybe i use and select image from other path, how can i do this action

**Comment by stefanhaustein** [comment]
Did you try a file:/// link with the full absolute path? They should just work if the app has access privileges for the corresponding path

**Comment by pishguy** [comment]
@stefanhaustein I'm so sorry sir, i don't try that, please let me to check that
