### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException without outer tag such as <html>

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#21]
@stefanhaustein hi, could you check this html code?

I'm using latest version of your library on `Gradle`
`text = "hello world <br/> <p style='text-align:left;'>this is an code</p> <br/> end of text <br/> and <p style='text-align:left;'>this my code</p> <br/> finish";`

I get this error:

`java.lang.RuntimeException: Unable to start activity ---: java.lang.RuntimeException: java.lang.RuntimeException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT hello world @1:13 in java.io.StringReader@36a75a9) `

My code:

```
try {
        text = "hello world <br/> <p style='text-align:left;'>this is an code</p> <br/> end of text <br/> and <p style='text-align:left;'>this my code</p> <br/> finish";
    
        Reader reader = new StringReader(text);
    
        HtmlView htmlView = new HtmlView(context);
        htmlProcessor.parse(reader, htmlView);
    
        ScrollView scrollView = new ScrollView(context);
        scrollView.addView(htmlView);
        markdownViewContent.addView(scrollView);
    } catch (Exception e) {
        e.printStackTrace();
        Log.e("HtmlView ", e.getMessage());
        throw new RuntimeException(e);
    }
```

**Comment by stefanhaustein** [comment]
Can you add an outer HTML (or body) tag, e.g. 


    text = "<html>hello world <br/> <p style='text-align:left;'>this is an code</p> <br/> end of text <br/> and <p style='text-align:left;'>this my code</p> <br/> finish</html>";

**Comment by pishguy** [comment]
@stefanhaustein adding outer tag resolved problem, but i'm not really sure text have outer tag

**Comment by 0x410c** [comment]
a string should not be parsed, @stefanhaustein, in this case the library is parsing a string as html also, thats not a correct behaviour

**Comment by stefanhaustein** [comment]
The code sets the XmlPullParser to relaxed mode, which should make it work regardless of the outer tag. Given that the exception comes from the XmlPullParser, there seems to be little i can do at the moment (long term solution might be to make sure an appropriate version of kxml gets bundled via gradle). One hack one could do is to always append an outer tag, or do a simple heuristic whether the string starts with "<" or perhaps "<html" in client code...

**Comment by stefanhaustein** [comment]
p.s. another option could be to re-try with an outer element added when there is an xml pull exception...

**Comment by pishguy** [comment]
@stefanhaustein thanks, i think wrapping text with `<p>` and `</p>` is simple than your hack
