### ISSUE TITLE
Style HtmlView

### ISSUE THREAD

**Issue by kevinvanmierlo** [stefanhaustein/HtmlView2#3]
I can't find how to properly style the HtmlView. It uses the CssStyleSheet, but I can't change anything about CssStyleSheet. 
Also I can't find out how to set the font size.

**Comment by stefanhaustein** [comment]
The fixed default style sheet is set up in CssStyleSheet.createDefault(). 

-  I'd like to keep the default as close to a common clean "reset" style sheet as possible. So you could try to convince me to change it with a reference to where it differs from established standards

- HtmlView itself has a "scale" variable that would affect the font size and that I could expose if that would help.

- If WebView has the functionality you are asking for, I might be willing to replicate it.

- You could inject a style tag or stylesheet reference into the rendered page

**Comment by kevinvanmierlo** [comment]
@stefanhaustein I would definitely keep the default stylesheet. That's great. Just make it accessible so I can make changes to it. For example I wanted to limit the indentation on lists. Then I want to get the CssStyleSheet from the HtmlView and make changes to the "ol" and "ul". So basically you already have the correct code, only the methods need to be accessible to edit a stylesheet.

I'd rather have a real font size. I want the font size to be the same as the rest of my app, for example 16sp. Is something like that possible?

**Comment by stefanhaustein** [comment]
I think the excessive ol/ul space issue is something that might need to get addressed in general in the default style sheet. Does WebView have an API to set the font size? What do you do there?

**Comment by kevinvanmierlo** [comment]
Yeah that's true, but not my point. The stylesheet you made is very awesome, but I can't do anything to access it. If the HtmlView created the default stylesheet, I should be able to change some of the values. Most default values should be good for most, but it's always nice to have a way to tweak those values.

Yes WebView has an API to set the font size: https://developer.android.com/reference/android/webkit/WebSettings.html#setDefaultFontSize(int)
Something like this would be good. 
And another suggestion: the TextView should have the project default textSize

**Comment by stefanhaustein** [comment]
I have added a WebView-like API for setting the default font size.
To change other aspects of the style sheet, you'll need to override HtmlView.createStyleSheet()

**Comment by kevinvanmierlo** [comment]
@stefanhaustein Thanks for the font size.

About the overriding. I'd rather not override anything. I should be able to use your library without overriding anything. So that's why I suggested to open up the CssStyleSheet (specifically the put method) so I can change the default css rules. And maybe add some other methods to get or remove a specific key in the stylesheet. Do you understand what I mean?

**Comment by stefanhaustein** [comment]
I see. I have made the put method public, so you should be able now to just call HtmlView.getStyleSheet() and change it.

**Comment by kevinvanmierlo** [comment]
@stefanhaustein awesome! One last thing is to also include a get method. Then you can get the CssStyleDeclaration and change just one thing instead of having to recreate the whole CssStyleDeclaration of that tag.

**Comment by stefanhaustein** [comment]
Ok, I have added a get method -- use at your own risk, I have only checked that it compiles O:)

If you are familiar with WebView, don't hesitate to file new issues for things that you think are important when using HtmlView as a drop-in replacement

**Comment by kevinvanmierlo** [comment]
@stefanhaustein Thanks for adding it! But you did check if it works right? If not people are going to be confused if it doesn't actually work

**Comment by stefanhaustein** [comment]
I'll replace put with get, that will make sure it works O:)

**Comment by kevinvanmierlo** [comment]
@stefanhaustein You don't have to replace it, just test it if it works ;). I would keep the put method, it could come in handy.

**Comment by stefanhaustein** [comment]
I have migrated the internal default setup to get() and deleted the (redundant) put method.

**Comment by kevinvanmierlo** [comment]
@stefanhaustein Looks good! Though you didn't have to remove the put method. It could come in handy if you want the override the entire css rule.
