### ISSUE TITLE
Click handlers, on clickable elements

### ISSUE THREAD

**Issue by 0x410c** [stefanhaustein/HtmlView2#4]
hey stefanhaustein,

first of all, you did a great job by creating this and i am currently using it in a project of mine.
back to the issue, can i set a click listener to clickable elements like buttons, or get input from edittext views?

if there is any option like that, i am enable to find one. 

thank you

**Comment by stefanhaustein** [comment]
You should be able to get access to the android views from the corresponding dom element via getView(). The dom can be accessed via getDocument() on HtmlView. To intercept links, subclass HtmlView and override openLink().

Let me know if you need more. Ideally, feature requests match functionality that's already available in WebView, so the library gets easier to use as a drop-in replacement.

**Comment by stefanhaustein** [comment]
Please re-open with more details if the suggested approach doesn't work for you

**Comment by 0x410c** [comment]
hello stefan,

sorry i got busy a little, i tired doing that u said,
Document = htmView.getDocument();

but still i am not able to get the corresponding view according to their id in html tag,

one more thing
what about tabs and list views any solution for that?

thanks

**Comment by stefanhaustein** [comment]
You'd need to scan the document using document.getDocumentElement, then using getFirstChild() etc.

Maybe it would be simpler to utilize the [RequestHandler](https://github.com/stefanhaustein/htmlview/blob/master/HtmlView/src/main/java/org/kobjects/htmlview/RequestHandler.java) in the original [HtmlView](https://github.com/stefanhaustein/htmlview)?

Not sure what you are referring to with list views and tabs?

**Comment by 0x410c** [comment]
i meant is their any option to create list or tabs through htmlview?

and what tags and css attributes are supported?
