### ISSUE TITLE
List types: Only decimal ones are working

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/HtmlView2#8]
I just tested the change made for #5, but only `<ol style="list-style-type:decimal;">` seems to be working as expected. Using `<ol style="list-style-type:lower-latin;">` the output looks incorrect.

[Decimal type](https://cloud.githubusercontent.com/assets/7279752/24345876/68e45530-12d2-11e7-9fbf-ab43fdf0b9e0.png)
[Lower latin type](https://cloud.githubusercontent.com/assets/7279752/24345875/66b4cf4c-12d2-11e7-8d24-8ddc5e45d702.png)

**Comment by stefanhaustein** [comment]
Ooops, should be fixed at head now.
