### ISSUE TITLE
org.kobjects.css.CssStyleDeclaration.isSet()' on a null object reference

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/HtmlView2#9]
this is my html:

```
<html>
<head>
    <title>HtmlView Demo</title>
</head>
<body>
<p style="text-align:left;direction:ltr;background-color: #ddf;">
    <strong>
         Simple HTML to Native
        <p> Native Components </p>
         Engine for Android
    </strong>
</p>
</body>
</html>
```

Error:

> Attempt to invoke virtual method 'boolean org.kobjects.css.CssStyleDeclaration.isSet(org.kobjects.css.CssProperty)' on a null object reference

**Comment by stefanhaustein** [comment]
It should no longer crash at head. Have added your example to the end of the demo HTML.

Can you please double check / confirm, so I can close the issue and release a new version?
